config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get '/home', to: 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/menu', to: 'static_pages#menu'

  get '/order', to: 'static_pages#order'

  get '/orderform', to: 'static_pages#orderform'

  get '/faq', to: 'static_pages#faq'

  get '/contact', to: 'static_pages#contact'

  get 'contact-me', to: 'messages#new', as: 'new_message'

  post 'contact-me', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message 
	include ActiveModel::Model
	attr_accessor :name, :email, :body
	validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
		@message = Message.new
	end

	def create
   		@message = Message.new message_params

	    if @message.valid?
	      MessageMailer.contact(@message).deliver_now
	      redirect_to new_message_url, notice: "Message received, thanks!"
	    else
	      render :new
	    end
	  end

	private

	def message_params
	   params.require(:message).permit(:name, :email, :body)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def menu
  end

  def order
  end

  def faq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "fully loaded" 
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!--Footer-->
 <div style="background-color: #F8F1D5; margin-top: 20px; padding-top:15px; padding-bottom: 15px;">
  <footer class="page-footer font-small blue pt-4 mt-4">
      <div class="container-fluid text-center text-md-left">
	          <div class="row">
	  
	              <!--First column-->
	              <div class="col-md-6">
	                  <h4 class="text-uppercase">Fully Loaded</h4>
	                  <p>Website made with &hearts; by <a href="http://www.davidin.me">David In</a>.</p>
	              </div>
	              <!--/.First column-->
	  
	              <!--Second column-->
	              <div class="col-md-6">
	                  <h4 class="text-uppercase">Links</h4>
	                  <ul class="list-unstyled">
						  <li><%= link_to "Contact", contact_path %></li>
						  <li><%= link_to "FAQ", faq_path %></li>
						  <li><a href="https://www.instagram.com/fullyloadedhopkins/">Instagram</a></li>
	                  </ul>
	              </div>
	              <!--/.Second column-->
	          </div>
	      </div>
	  <!--/.Footer Links-->
	  <!--Copyright-->
	  <div class="footer-copyright py-3 text-center">
	      <div class="container-fluid">
	          © 2018 Copyright: Fully Loaded

	      </div>
	  </div>
	  <!--/.Copyright-->
  
  </footer>
  <!--/.Footer-->
</div>

app/views/layouts/_header.html.erb
	<div id="navbar">
       <!-- Toggler/collapsible Button -->
        
        <!-- Navbar links -->
        <ul>
  				<li><%= link_to "home", root_path %></li>
  				<li><%= link_to "about", about_path %></li>
          <li><%= link_to "menu", menu_path %></li>
          <!-- photo in center -->
           <li><a href="home">
            <%= image_tag("logo.png", height: '120', width: '120') %>
           </a></li>
          <li><%= link_to "order", order_path %></li>
          <li><%= link_to "faq", faq_path %></li>
          <li><%= link_to "contact", contact_path %></li>
      </ul>
	</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	  </script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
   <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.email_field :email, placeholder: 'email' %>
  <%= f.text_area :body, placeholder: 'body' %>
  <%= f.submit 'Send' %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "about") %>
<div class="short-width center-block">
	<h1 class="text-center center-block">who we are</h1>
		<p class="text-center center-block space-below">Fully Loaded is a student run business that sells gourmet french fries during the late nights of weekends. Our fries are made with fresh ingredients and with the caring love of those who are passionate about cooking. </p>

	<h2>Meet the Makers</h2>

	<div class="content">
		<%= image_tag("emma.jpg", height: '170', width: '170', alt: "emma", :class => "float") %>
		<div class="bio">
			<h4>Emma Zeng, CEO</h4>
				<p>Emma Zeng is currently a junior at Johns Hopkins University who loves to cook when she's not studying for med school. She began Fully Loaded because she wanted to experiment with different flavors and try out new things. It was a hobby at first, but then her friends convinced her to make it into a business. </p>
		</div>
	</div>

	<div class="content">
		<%= image_tag("tracy.jpg", height: '170', width: '170', alt:"tracy", :class => "float") %>
		<div class="bio">
			<h4>Tracy Gao, CMO</h4>
				<p>Tracy Gao is an amateur photographer and graphic designer who wanted to see how far Fully Loaded would get her. She enjoys uploading to its Instagram often. </p>
		</div>
	</div>

	<div class="content">
		<%= image_tag("willa.jpg", height: '170', width: '170', alt:"willa", :class => "float") %>
		<div class="bio">
			<h4>Willa Yu</h4>
				<p>Willa Yu is always organizing and trying out new things. She loves helping out people, and took up the opportunity to expand Fully Loaded by helping out with orders and delivering to different locations.</p>
		</div>
	</div>

</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "contact") %>
<h1 class="text-center center-block" style="margin-right:22px">contact</h1>
<form class="text-center center-block">
	<h4>name</h4>
		<input type="text" class="text-center center-block">
		</input>
	<h4>e-mail</h4>
		<input type="text" class="text-center center-block">
		</input>
	<h4>subject</h4>
		<input type="text" class="text-center center-block">
		</input>
	<h4>message</h4>
		<input type="text" class="text-center center-block">
		</input>
	<h5 class="btn btn-primary" style="margin-top:45px">submit</h5>
</form>

app/views/static_pages/faq.html.erb
<% provide(:title, "fully loaded | faq") %>
<div class="short-width center-block">
	<h1 class="text-center center-block" style="padding-bottom: 45px; margin-right: 19px;">faq</h1>

		<h3 class="question">where do your ingredients come from?</h3>
		<p class="answer">Our ingredients come from various sources: the weekly farmer's market, eddie's grocery market, and Giant's. We buy our weekly supply of potatoes from the farmer's market, and buy other ingredients that we use to season our potatoes from Eddie's and Giant's.</p>

		<h3 class="question">how do you make such awesome fries?</h3>
		<p class="answer">They all come from the genius head of Emma Zeng, who reportedly has over 30 french fry recipes she's waiting to try out. You can also find the recipes of many of the french fries we serve. Emma likes to put her own twist on them. </p>

		<h3 class="question">how do I order this?</h3>
		<p class="answer">There are two ways you can order. You can either use the order form that can be found in the order page of this website, or you can text us at <a href="tel:1-908-349-4094">(908) 349-4094</a>. Choose whatever is most convenient for you! </p>

		<h3 class="question">can I order multiple fries for a group?</h3>
		<p class="answer">If you want to order multiple fries for a group, then all you have to do is order in advance, and Emma will prepare that group order from 30 to 45 minutes. </p>
</div>

app/views/static_pages/home.html.erb
<div class="row">
	<div class="column">
		<%= image_tag("front1.jpg", height: '100%', width: '100%', alt: "donut fries from the top view") %>
	</div>

	<div class="column">
		<%= image_tag("front2.jpg", height: '100%', width: '100%', alt: "animal fries on the top") %>
	</div>

	<div class="column">
		<%= image_tag("front3.jpg", height: '100%', width: '100%', alt: "cheetos fries on the top") %>
	</div>

	<div class="column">
		<%= image_tag("front4.jpg", height: '100%', width: '100%', alt: "margherita fries on the top") %>
	</div>

	<div class="column">
		<%= image_tag("front5.jpg", height: '100%', width: '100%', alt: "bahn mi fries on the top") %>
	</div>
</div>

app/views/static_pages/menu.html.erb
<% provide(:title, "menu") %>
<div class="medium-width center-block">
	<h1 class="text-center center-block" style="padding-bottom: 40px;">menu</h1>
		<div class="food">
			<%= image_tag("bahnmi.jpg", height: '50%', width: '50%', alt: "bahnmi fries", :class => "float") %>
				<div class = "description">
					<h3>bahn mi fries</h3>
						<p>Crispy, crunchy and topped with everything good inside a banh mi, these fries are fusion (ugh, does anyone else dislike the word fusion when describing food? But what else do we call it?!) food at its best. You will not regret ordering these to die for fries, and have no guilt over the calories as well.</p>
				</div>
		</div>

		<div class="food">
			<%= image_tag("margherita.jpg", height: '50%', width: '50%', alt: "emma", :class => "float") %>
				<div class="description">
					<h3>margherita pizza fries</h3>
						<p>These fries are coated with the finest margherita cheese you can find in Baltimore. When that cheese melts over the fries and the tomatoes char ever so slightly from the extra oven time, you have yourself some delicious margherita pizza fries. </p>
				</div>
		</div>


		<div class="food">
			<%= image_tag("donut.jpg", height: '50%', width: '50%', alt: "emma", :class => "float") %>
			<div class="description">	
				<h3>doughnut fries</h3>
					<p>These fries are those who have a sweet tooth. After being fried to a crispy edge, these balls of dough are coated in powdered sugar and chocolate. To finish it off, a slight sprinkle of cut strawberring is put on them. </p>
			</div>
		</div>

		<div class="food">
			<%= image_tag("cheetos.jpg", height: '50%', width: '50%', alt: "emma", :class => "float") %>
			<div class="description">
				<h3>hot cheetos fries</h3>
					<p>Cheetos and french fries. What more do we have to say? Experience the delight of the spicy crunchiness of the cheetos combined with the crispy delight of hot french fries. This certainly is a great way to end the night. </p>
			</div>
		</div>

		<div class="food">
		<%= image_tag("animal.jpg", height: '50%', width: '50%', alt: "emma", :class => "float") %>
			<div class="description">
				<h3>animal fries</h3>
					<p>Remember whenever you got so excited ordering those animal fries in the In-n-Out, as if you were the only one that knew about them. Well now you can re-experience that feeling by ordering these right now. Never had In-n-Out animal fries? Well you're in for quite the treat!</p>
			</div>
		</div>
</div>

app/views/static_pages/order.html.erb
<% provide(:title, "order") %>
<h1 class="text-center center-block" style="padding-bottom: 40px;">ordering</h1>
		<div class="float info" style="margin-right: 6.3%;">
			<h5 class ="spacing-1">choose your fries.</h5>
			<p class ="spacing-2">Fully Loaded offers a wide variety of fries. Choose your favorite to get started!</p>
			<%= link_to "menu", menu_path, class: "btn btn-primary" %>
		</div>
		<%= image_tag("step1.png", height: '28%', width: '28%', alt: "photo of all the fries", class: "rounded-corners") %>

	<div class="float info" style="margin-right: 10.65%;">
		<h5 class ="spacing-1">text or fill out a form.</h5>
		<p class ="spacing-2">Text <a href="tel:1-908-349-4094">(908) 349-4094</a> what you want and we’ll start cooking asap. If you
		prefer ordering through our website, please press the button below.</p>
		<%= link_to "order", orderform_path, class: "btn btn-primary" %>
	</div>
	<%= image_tag("step2.png", height: '20%', width: '20%', alt: "photo of iphone text", class: "rounded-corners") %>

	<div class="float info" style="margin-right: 3%;">
		<h5 class ="spacing-1">pick up your order.</h5>
		<p class ="spacing-2">Your order will be ready in 10 to 15 minutes later. Come pick up your
		delicious fries at the front entrance of Village Lofts.</p>
	</div>
	<%= image_tag("step3.jpg", height: '35%', width: '35%', alt: "photo of margeherita fries", class: "rounded-corners") %>

app/views/static_pages/orderform.html.erb
<% provide(:title, "order form") %>
<h1 class="text-center center-block" style="margin-right:22px">your order</h1>
<form class="text-center center-block">
	<h4>name</h4>
		<input type="text" class="text-center center-block">
		</input>
	<h4>phone</h4>
		<input type="text" class="text-center center-block">
		</input>
	<h4>which fry do you want? <br/> <p style="font-size:12px">(just type them out)</style></h4>
		<input type="text" class="text-center center-block">
		</input>
	<h4>how many of those?</h4>
		<input type="text" class="text-center center-block">
		</input>
	<h5 class="btn btn-primary" style="margin-top:45px">submit</h5>
</form>